### ISSUE TITLE
The path 'A' either does not exist or is not a valid file system path.

### ISSUE THREAD

**Issue by HenyPotter** [PowerShell/Microsoft.PowerShell.Archive#113]
![image](https://user-images.githubusercontent.com/60482905/151248678-e11aeb7b-7e5d-4667-b879-b307be759a31.png)
I would love to ask you if there's any way to fix this problem, I'm really hopeless 💛

**Comment by ayousuf23** [comment]
We need more information to replicate this bug. Is `A` in your working directory?

**Comment by HenyPotter** [comment]
Found the problem, you can close it.
