### ISSUE TITLE
Add Tar support to PowerShell with the new .NET 7.0 APIs

### ISSUE THREAD

**Issue by carlossanlop** [PowerShell/Microsoft.PowerShell.Archive#116]
### Summary of the new feature / enhancement

I am working on adding new Tar APIs in .NET 7.0: https://docs.microsoft.com/en-us/dotnet/api/system.formats.tar?view=net-7.0

It would be great if we could offer Cmdlets in PowerShell for these APIs, both for archiving (`*.tar`) and for archiving + compressing (`*.tar.gz`).

How can I help to make this happen?

@SteveL-MSFT @iSazonov 

### Proposed technical implementation details (optional)

Here is a detailed explanation of how the APIs can be used as of .NET 7.0 Preview 4: https://github.com/dotnet/core/issues/7378#issuecomment-1111474529

Note: There will be some minor API changes in the next Previews, but most of the functionality is like in the linked comment.

#### Known bugs

I created this uber issue to track pending feedback to address: https://github.com/dotnet/runtime/issues/68230

**Comment by SteveL-MSFT** [comment]
@carlossanlop we've planning on rewriting the Archive module and likely leveraging the new .NET 7 APIs and adding tar support
