### ISSUE TITLE
Make Microsoft.PowerShell.Archive compatible with PowerShell 3.0

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/Microsoft.PowerShell.Archive#14]
Microsoft.PowerShell.Archive currently requires PowerShell 5.0 or later, but there is no need to have such a high requirement.  This module can be written such that it requires PowerShell 3.0 or later.  This issue is to track that need so that this module can be made available to downlevel versions of PowerShell.

**Comment by KirkMunro** [comment]
It turns out this may simply be something to test. The first open source version of this module used ::new in a bunch of places. It seems this changed, so maybe PS3 support is already there (in which case this can be closed). I'll investigate later.

**Comment by SteveL-MSFT** [comment]
We removed dependencies on PS5 already before we made it OSS and I believe I tested it against PS4.  Not sure about PS3.  If you can verify it works on PS3, we should make this a doc bug.

**Comment by anmenaga** [comment]
I've verified that current code of the module and tests run fine on PSVersion 3.0 (Windows Server 2012 Standard).
