### ISSUE TITLE
Add support for Zip64 for archives > 4GB

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/Microsoft.PowerShell.Archive#19]
The .Net ZipFile class currently has a limitation of 2GB sizes, this limits usefulness on VM scenarios where VHDs are routinly larger than 2 GB

**Comment by iSazonov** [comment]
@SteveL-MSFT Do you have in mind that we need to use this project [SharpZipLib](https://github.com/icsharpcode/SharpZipLib#sharpziplib----)?

**Comment by SteveL-MSFT** [comment]
@iSazonov since SharpZipLib appears to be available under MIT License, I see no reason to not use that lib.

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks! 
😕 they haven't .Net Core support https://github.com/icsharpcode/SharpZipLib/issues/106
 It is seems  we are still blocked in both cases.

**Comment by SteveL-MSFT** [comment]
Looks like SharpZipLib now has NetStandard1.3 support so that works for us

**Comment by kilasuit** [comment]
@SteveL-MSFT is there any update on this at all?

**Comment by SteveL-MSFT** [comment]
@kilasuit no update right now, it's in the backlog, but not a high priority right now given other work that's happening

**Comment by rjmholt** [comment]
I can't find a corefx issue for this? Is this something we should open an issue on them for?

**Comment by rjmholt** [comment]
I can't find a corefx issue for this? Is this something we should open an issue on them for?

Some possibly related issues:
- https://github.com/dotnet/corefx/issues/11668
- https://github.com/dotnet/corefx/issues/24083
- https://github.com/dotnet/corefx/issues/11669

**Comment by SteveL-MSFT** [comment]
@rjmholt I think rewriting this module in C# and using SharpZipLib might be better than waiting for corefx

**Comment by rjmholt** [comment]
@SteveL-MSFT agreed, but just want corefx to be conscious of the ask

**Comment by SteveL-MSFT** [comment]
@rjmholt no harm in opening an issue for corefx.  I suspect it's not high on their priority since existing OSS libraries support zip better than the built in support unless ASPNETCORE has a need for it.

**Comment by adam-birds-hwt** [comment]
Any update on where this is at?

**Comment by SteveL-MSFT** [comment]
@adam-birds-hwt unfortunately, this is currently not in our priority queue.  I'd like to see about addressing this in PS7.1 timeframe as it's not a small work item.

**Comment by boscorelly** [comment]
Hi, same issue on windows Server 2016/2019

**Comment by iSazonov** [comment]
[This comment](https://github.com/dotnet/dotnet-api-docs/issues/834#issuecomment-425173006) says that .Net support Zip64.
After [the fix](https://github.com/dotnet/corefx/pull/36027) I'd expect that the module works in PowerShell 7.0.

@ericstj or @ianhays could tell us (please) where a problem is in this module and that API we could use to re-write the module on C#.

**Comment by ericstj** [comment]
The implementation in .NETCore still loads into memory when being opened for *update*.  When it does this it uses a managed array which limits the size to 2GB.  

If you open only the archive for *Read* or *Write* only, then entries can be created that exceed 2GB.  Let us know more about the scenario and we can provide a recommendation.

**Comment by rjmholt** [comment]
@adityapatwardhan does the archive module perform archive update/modification functions?

**Comment by iSazonov** [comment]
@rjmholt Yes, it is does.

If MSFT approves I'd port the module to C# (in PowerShell/Module repo) and address the issue too.

**Comment by rjmholt** [comment]
@SteveL-MSFT and @adityapatwardhan are probably the right people to make that call

**Comment by ChrisLynchHPE** [comment]
Any status update on this, and https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/96?  It would be great to not have to build some custom Advanced Function to handle archives, or worse yet to use an external binary (like 7z.exe).

**Comment by michalzobec** [comment]
we waiting for creating of ZIP archives almost for 4 years ... it is sad. :(

**Comment by iSazonov** [comment]
In .Net 5.0 I still see issues in the API. We need investigate in depth all issues in the API and ask .Net team to fix its in .Net 6.0 milestone.

**Comment by kilasuit** [comment]
@Bearstonk - I believe that this is semi-planned in the [PowerShell Roadmap post](https://devblogs.microsoft.com/powershell/powershell-and-openssh-team-investments-for-2022/) by @SteveL-MSFT due to the Exec Order on CyberSecurity.

How soon this happens will be a different matter that only Steve can properly comment on.

**Comment by ayousuf23** [comment]
Closing this issue as zip64 is now supported.

**Comment by ayousuf23** [comment]
Please download the latest preview for zip64 support.

**Comment by JairoCaychoFinTech** [comment]
@ayousuf23 Could you give me more context, what does it mean to download latest preview for zip64?

**Comment by JairoCaychoFinTech** [comment]
For all the ones that ended up here I found a solution without upgrading to the just released (4 days ago) preview version .NET Framework 4.8.1.
You can download the latest (as today 13 of August 2022 is 6.0.4) .NET open-source developer platform from:
https://dotnet.microsoft.com/en-us/download/dotnet

Then in your powershell you go to the folder where is your downloaded script and execute the following command:
`.\dotnet-install.ps1 -Channel Current`
If you want to check that everything is of, just run:
`dotnet --list-sdks`

And you should get something like this:
![image](https://user-images.githubusercontent.com/106173351/184509009-ea47c321-1d83-4fba-9063-fbdff6c50ec8.png)

**Comment by kilasuit** [comment]
@JairoCaychoFinTech what @ayousuf23 meant was with the latest preview of this module you now get zip64 support, which the release of it on the [PowerShellGallery](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Archive/2.0.1-preview2) which shows install instructions

**Comment by JairoCaychoFinTech** [comment]
> @JairoCaychoFinTech what @ayousuf23 meant was with the latest preview of this module you now get zip64 support, which the release of it on the [PowerShellGallery](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Archive/2.0.1-preview2) does show install instructions

Thanks for the clarification. I'm just starting with scripting so I need a lot of explanations!

**Comment by santysq** [comment]
For anyone still facing this issue and wanting to use a PowerShell / .NET native solution, I created [this function](https://github.com/santysq/Compress-File). It is fully compatible with PowerShell 5.1 and PowerShell Core and there shouldn't be a file size limitation because it doesn't use a [`MemoryStream`](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream.-ctor?view=net-6.0), instead it copies from [`FileStream`](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream?view=net-6.0) to `IO.Compression.WrappedStream`. I haven't encountered a size limitation so far and is a lot faster that the Core version of `Compress-Archive` (haven't tested the preview version of the cmdlet yet).

**Comment by santisq** [comment]
@NRL-LEastham I'm honestly unable to replicate. Have tried to compress folders with size up to 20Gb without any problems. Are you using the latest module version `1.0.4`?  If you want to please raise an Issue in the repo to troubleshoot.

**Comment by NRL-LEastham** [comment]
> > I've just tried this on a 3.7GB file and it cuts the original file short as the CopyTo has the same Stream was too long issue. The archive completes but only with 2GB of the original file.
> 
> @NRL-LEastham I'm honestly unable to replicate. Have tried to compress folders with size up to 20Gb without any problems. Are you using the latest module version `1.0.4`? If you want to please raise an Issue in the repo to troubleshoot.

Sorry was against the clock on Friday.  I ended up just using a function call that adds the switches to the command line of the installed 7z CLI. Was on the latest version and my 3.7gb T-SQL file just generated the stream error on a CopyTo command instead. Was a 2 vCore 8GB VM and although the zip was created the original file size was reported as 2.7GB instead so must have truncated.  If I get time I'll test on my local machine and if still an issue will raise it on your repo.
