### ISSUE TITLE
Unix CI builds

### ISSUE THREAD

**Issue by vors** [PowerShell/Microsoft.PowerShell.Archive#24]
I started decoupling Archive from PS/PS in https://github.com/PowerShell/PowerShell/pull/2743

To guarantee that we are running tests on Unix, we should migrate https://github.com/PowerShell/PowerShell/blob/471594c6ab97622d2d622cbb0ef057f58a46be2a/test/powershell/Modules/Microsoft.PowerShell.Archive/Pester.Commands.Cmdlets.Archive.Tests.ps1 and enable Travis CI for this project.

**Comment by anmenaga** [comment]
Fixed; module and tests updated; Travis CI enabled.
