### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by eugeneniemand** [PowerShell/Microsoft.PowerShell.Archive#28]
when executing 
`[System.IO.Compression.ZipFile]::CreateFromDirectory("$publishFolder", "$publishFolder/deployPackage.zip")`

I get the following error:
```
Exception calling "CreateFromDirectory" with "2" argument(s): "The process cannot access the file '../projects/data/kinesisToSql/bin/Debug/netcoreapp1.1/publish/deployPackage.zip' because it is
being used by another process."

```
This is impossible as the file does not exist before running the command

**Comment by joeyaiello** [comment]
This repository is for the Archive cmdlets that ship in PowerShell 5.0 and [in the Gallery](https://www.powershellgallery.com/packages/Microsoft.PowerShell.Archive) for 3.0/4/0, not usage of `System.IO.Compression` in PowerShell.

Have tried just using `Compress-Archive` instead?

**Comment by VishnuKiranBodugu** [comment]
Compress-Archive will not maintain folder structure
