### ISSUE TITLE
Expand-Archive does not return a System.IO.FileInfo nor System.IO.DirectoryInfo

### ISSUE THREAD

**Issue by inwenis** [PowerShell/Microsoft.PowerShell.Archive#38]
The docs (https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.archive/expand-archive) say that Expand-Archive should return a System.IO.FileInfo or System.IO.DirectoryInfo but it has no output

**Comment by sdwheeler** [comment]
This was fixed in MicrosoftDocs/PowerShell-Docs#3696 on Feb 12. You need to run Update-Help -Force to get the new help files.

**Comment by sdwheeler** [comment]
This is a duplicate of issue #9.
