### ISSUE TITLE
Implement PassThru parameter for Compress-Archive

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/Microsoft.PowerShell.Archive#4]
Copied from [a UserVoice suggestion](http://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11340771-compress-archive-add-a-passthru-parameter) filed by Francois-Xavier Cat

"It would be great to have the parameter Passthru when using the Compress-Archive function from the Microsoft.PowerShell.Archive module.

I would expect a System.IO.FileInfo object in the output"

**Comment by DDog80sRocked** [comment]
What version of 5.x has the -PassThru option with the Expand-Archive cmdlet?  Currently running 5.1.17134.858 and there's no option for this.

**Comment by SergiuEnachi** [comment]
> What version of 5.x has the -PassThru option with the Expand-Archive cmdlet? Currently running 5.1.17134.858 and there's no option for this.

@DDog80sRocked just run: Install-Module Microsoft.PowerShell.Archive -Force
this will install **v1.2.5** (overwriting the older version) of the Archiving function witch adds **-PassThru** parameter
Tested on PS v5.1.19041.610
