### ISSUE TITLE
All path separators needs to be normalized to forward slash

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/Microsoft.PowerShell.Archive#48]
Even on Windows, the archive contents should only use forward slash as directory separator otherwise it causes problems on non-Windows systems where backslash is a valid character in a filename.

According to the [Zip file spec](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) section 4.4.17.1, the path MUST only use forward slashes

**Comment by anmenaga** [comment]
Fixed in module version 1.2.3.0
`Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force`
