### ISSUE TITLE
Expand-Archive: A parameter cannot be found that matches parameter name 'DestinationPath'

### ISSUE THREAD

**Issue by gmahender** [PowerShell/Microsoft.PowerShell.Archive#52]
When expanding zip file with -DestinationPath parameter, cmdlet is throwing error - see below for detailed error message.
My environment is Windows 10 x64 (build 16299).

```
F:\1> Expand-Archive -Path abc.zip -DestinationPath f:\1\temp
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
At line:1 char:32
+ Expand-Archive -Path .\abc.zip -DestinationPath f:\1\temp
+                                ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```
  

```
F:\1> Expand-Archive -LiteralPath f:\1\abc.zip -DestinationPath f:\1\temp
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
At line:1 char:42
+ Expand-Archive -LiteralPath f:\1\abc.zip -DestinationPath f:\1\temp
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```

**Comment by anmenaga** [comment]
@gmahender  Looks like you are running `Expand-Archive` cmdlet from `Pscx` module, not from `Microsoft.PowerShell.Archive` module.

**Comment by gmahender** [comment]
Thanks for catching my silly mistake. 
I was able to unzip with -outputpath parameter.

`Expand-Archive -Path .\abc.zip -OutputPath f:\1`

**Comment by tomerMP** [comment]
I have run into the same issue.
This is a bit of an annoyance because on some systems Microsoft.PowerShell.Archive is used and DestinationPath works, but in other systems Pscx module is used and OutputPath works.

I need a way to standardize which module is used so my code doesn't have to take into account both.
Is there any way I can specify that my cmdlet use Microsoft.PowerShell.Archive instead of Pscx?

**Comment by megamorf** [comment]
@tomerMP You can call a function from a specific module by prepending it with the module name. 

So `Expand-Archive -DestinationPath` 
becomes 
`Microsoft.PowerShell.Archive\Expand-Archive -DestinationPath`

**Comment by tomerMP** [comment]
@megamorf , Thanks a ton!!! Solved my issue
