### ISSUE TITLE
Enable extraction of ZIPs with non-zip extensions

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/Microsoft.PowerShell.Archive#6]
This was originally posted by alejandro5042 on Connect and [now lives on UserVoice](http://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088498-expand-archive-ps1-should-unzip-non-zip-formats-wi):

> There are many file formats that are actually just .zip files but with different extensions. For example, NuGet packages are really zip files with the .nupkg extension. My company (National Instruments) has many of these types of formats, as does Microsoft with their Office formats, and many other companies.

> It's silly to have to copy/rename the file to have a .zip to have this cmdlet extract the contents. I suggest removing the .zip file check in all these cmdlets. If it can't extract it, you can error out. If supporting different archive formats is in the future, you can specify the algorithm in a parameter if it cannot be inferred from the file extension. By default, it can be .zip.

**Comment by KirkMunro** [comment]
FYI, I fixed this in a clone over the weekend and will submit a pull request shortly.
