### ISSUE TITLE
Unable to compress hidden files with Compress-Archive

### ISSUE THREAD

**Issue by LanceUMatthews** [PowerShell/Microsoft.PowerShell.Archive#66]
The following code demonstrates two issues:

1. When passing a directory to the `-Path` parameter of `Compress-Archive`, any hidden files are silently ignored; they are neither present in the output file nor mentioned in the `-Verbose` output.  (This behavior is also not mentioned in [the documentation](https://docs.microsoft.com/powershell/module/microsoft.powershell.archive/compress-archive).)
2. When passing hidden files to the `-Path` parameter of `Compress-Archive`...
    - ...in PowerShell the first hidden file encountered causes errors to be thrown and output file creation to fail.
    - ...in PowerShell Core output file creation succeeds but each hidden file encountered causes an error to be thrown and the corresponding compressed file entry has its modification timestamp set to `1980-01-01`.

Code to reproduce:

    $directoryToCompress = New-Item -ItemType Directory -Path 'Input';
    $filesToCompress = @();

    foreach ($id in 1..5)
    {
        $file = New-Item -ItemType File -Path $directoryToCompress -Name "$id.txt" -Value "Hello, World!  This is file #$id.";
        if ($id % 2 -eq 0)
        {
            $file.Attributes = $file.Attributes -bor [System.IO.FileAttributes]::Hidden;
        }

        $filesToCompress += $file;
    }

    $PSVersionTable;

    Compress-Archive -Path $directoryToCompress -DestinationPath 'FromDirectory.zip' -Verbose;
    Compress-Archive -Path $filesToCompress     -DestinationPath 'FromFiles.zip'     -Verbose;

PowerShell console output:

	Name                           Value
	----                           -----
	PSVersion                      5.1.17763.134
	PSEdition                      Desktop
	PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
	BuildVersion                   10.0.17763.134
	CLRVersion                     4.0.30319.42000
	WSManStackVersion              3.0
	PSRemotingProtocolVersion      2.3
	SerializationVersion           1.1.0.1
	VERBOSE: Preparing to compress...
	VERBOSE: Performing the operation "Compress-Archive" on target "C:\Compress-Archive test\Input".
	VERBOSE: Adding 'C:\Compress-Archive test\Input\1.txt'.
	VERBOSE: Adding 'C:\Compress-Archive test\Input\3.txt'.
	VERBOSE: Adding 'C:\Compress-Archive test\Input\5.txt'.
	VERBOSE: Preparing to compress...
	VERBOSE: Performing the operation "Compress-Archive" on target "
	C:\Compress-Archive test\Input\1.txt
	C:\Compress-Archive test\Input\2.txt
	C:\Compress-Archive test\Input\3.txt
	C:\Compress-Archive test\Input\4.txt
	C:\Compress-Archive test\Input\5.txt".
	VERBOSE: Adding 'C:\Compress-Archive test\Input\1.txt'.
	Get-Item : Could not find item C:\Compress-Archive test\Input\2.txt.
	At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:814 char:63
	+ ... Entry.LastWriteTime = (Get-Item -LiteralPath $currentFilePath).LastWr ...
	+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : ObjectNotFound: (C:\Compress-Archive test\Input\2.txt:String) [Get-Item], IOException
		+ FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetItemCommand

	VERBOSE: The partially created archive file 'C:\Compress-Archive test\FromFiles.zip' is deleted as it is not usable.
	Exception setting "LastWriteTime": "Cannot convert null to type "System.DateTimeOffset"."
	At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:814 char:25
	+ ...             $currentArchiveEntry.LastWriteTime = (Get-Item -LiteralPa ...
	+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
		+ FullyQualifiedErrorId : ExceptionWhenSetting

PowerShell Core console output:

    Name                           Value
    ----                           -----
    PSVersion                      6.1.1
    PSEdition                      Core
    GitCommitId                    6.1.1
    OS                             Microsoft Windows 10.0.17763
    Platform                       Win32NT
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0
    VERBOSE: Preparing to compress...
    VERBOSE: Performing the operation "Compress-Archive" on target "C:\Compress-Archive test\Input".
    VERBOSE: Adding 'C:\Compress-Archive test\Input\1.txt'.
    VERBOSE: Adding 'C:\Compress-Archive test\Input\3.txt'.
    VERBOSE: Adding 'C:\Compress-Archive test\Input\5.txt'.
    VERBOSE: Preparing to compress...
    VERBOSE: Performing the operation "Compress-Archive" on target "
    C:\Compress-Archive test\Input\1.txt
    C:\Compress-Archive test\Input\2.txt
    C:\Compress-Archive test\Input\3.txt
    C:\Compress-Archive test\Input\4.txt
    C:\Compress-Archive test\Input\5.txt".
    VERBOSE: Adding 'C:\Compress-Archive test\Input\1.txt'.
    Get-Item : Could not find item C:\Compress-Archive test\Input\2.txt.
    At C:\program files\powershell\6\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:831 char:43
    + ...      $lastWriteTime = (Get-Item -LiteralPath $currentFilePath).LastWr ...
    +                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Compress-Archive test\Input\2.txt:String) [Get-Item], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetItemCommand

    WARNING: 'C:\Compress-Archive test\Input\2.txt' has LastWriteTime earlier than 1980. Compress-Archive will store any files with LastWriteTime values earlier than 1980 as 1/1/1980 00:00.
    VERBOSE: Adding 'C:\Compress-Archive test\Input\2.txt'.
    VERBOSE: Adding 'C:\Compress-Archive test\Input\3.txt'.
    Get-Item : Could not find item C:\Compress-Archive test\Input\4.txt.
    At C:\program files\powershell\6\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:831 char:43
    + ...      $lastWriteTime = (Get-Item -LiteralPath $currentFilePath).LastWr ...
    +                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Compress-Archive test\Input\4.txt:String) [Get-Item], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetItemCommand

    WARNING: 'C:\Compress-Archive test\Input\4.txt' has LastWriteTime earlier than 1980. Compress-Archive will store any files with LastWriteTime values earlier than 1980 as 1/1/1980 00:00.
    VERBOSE: Adding 'C:\Compress-Archive test\Input\4.txt'.
    VERBOSE: Adding 'C:\Compress-Archive test\Input\5.txt'.

The `Get-Item` errors reference the following lines in the `ZipArchiveHelper` function:

    # Updating  the File Creation time so that the same timestamp would be retained after expanding the compressed file.
    # At this point we are sure that Get-ChildItem would succeed.
    $lastWriteTime = (Get-Item -LiteralPath $currentFilePath).LastWriteTime

**Comment by cmruffin** [comment]
A problem for zipping up git repos...

**Comment by MattJeanes** [comment]
I'm seeing platform disparity for this too with regards to unix dotfiles e.g. `.env` where PowerShell 7 on Windows will happily include them but on Linux it will silently omit them from the archive. Had to workaround for now by renaming it to something else and renaming it back on the target.

Repro: PowerShell 7 on Ubuntu
1. Create a folder /tmp/compressme
2. Put an .env file inside the folder
3. Open pwsh and use Compress-Archive on the folder
4. The resulting zip file does not contain the .env file

**Comment by lucmoco** [comment]
Same Problem here. I'm trying to update a SharePoint Framework package (a .sppkg file which is in fact a ZIP archive) in a DevOps release on Linux. My process is as follows:

- Uncompress the files using the `Expand-Archive` cmdlet
- Update a package file
- Build an updated version of the package with `Compress-Archive`.

The problem is that the package contains a `_rels/.rels` file which gets lost in the process. Thus the resulting package is invalid and its installation fails.

**Comment by davetapley** [comment]
@ayousuf23 is there a plan to release v2? 🤞🏻

**Comment by mklement0** [comment]
Indeed, it would be good to know:
* when this fix will land
* as well as what future PowerShell version the fix will be bundled with.

The currently available _preview_ version does seem to have the fix (confusingly, the release notes only talk about _empty_ directories, but those are already included in the latest stable version).

* https://github.com/PowerShell/Microsoft.PowerShell.Archive/releases/tag/v2.0.1-preview1

However, the PowerShell Gallery package for this preview release has been _unlisted_, suggesting there was a problem with it.

* https://www.powershellgallery.com/packages/Microsoft.PowerShell.Archive/2.0.1-preview2

That said, if you're adventurous and  know the exact version, you can still install it:

```powershell
Install-Module -Name Microsoft.PowerShell.Archive -RequiredVersion 2.0.1-preview2 -AllowPrerelease
```
