### ISSUE TITLE
`Compress-Archive` generates zip files that fail in non-Windows environment

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Microsoft.PowerShell.Archive#71]
**Edit**:

This is likely a dupe, caused by Powershell 6.2 shipping a broken `compress-archive` even though it's been fixed. See https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/62#issuecomment-479873445

If someone knows how to update compress-archive on 6.2 (`Update-Module Microsoft.PowerShell.Archive` won't work because it comes with powershell) please let me know.

-----

Related to https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/11, which seems to be about Compress-Archive on non-Windows platforms.

Using Powershell 6.2 **on Windows**, Compress-Archive generates zip files that do not extract properly on non-Windows environments - in my case, AWS.

# Windows Explorer and write-zip use /, and work in both Windows and non-Windows platforms

Generated archives that work on AWS: 
 - Using Windows Send To -> Compresseed (zipped) folder works
 - Using write-zip cmdlet

```
$ unzip -l ~/send-to-compressed-folder-good.zip
Archive:  /home/mike/send-to-compressed-folder-good.zip
    Length      Date    Time    Name
---------  ---------- -----   ----
        1692  2019-04-03 17:13   index.js
        305   2019-04-03 16:25   node_modules/.bin/semver
        182   2019-04-03 16:25   node_modules/.bin/semver.cmd
        460   1985-10-26 09:15   node_modules/bson/bower.json
        540949  1985-10-26 09:15   node_modules/bson/browser_build/bson.js
        357   1985-10-26 09:15   node_modules/bson/browser_build/package.json
        7674  1985-10-26 09:15   node_modules/bson/HISTORY.md
        1457  1985-10-26 09:15   node_modules/bson/index.js\
```
and
```
$ unzip -l ~/write-zip-good.zip
Archive:  /home/mike/write-zip-good.zip
Length      Date    Time    Name
---------  ---------- -----   ----
        0  2019-04-03 16:25   node_modules/
        0  2019-04-03 16:25   node_modules/.bin/
      305  2019-04-03 16:25   node_modules/.bin/semver
      182  2019-04-03 16:25   node_modules/.bin/semver.cmd
        0  2019-04-03 16:25   node_modules/bson/
      460  1985-10-26 09:15   node_modules/bson/bower.json
        0  2019-04-03 16:25   node_modules/bson/browser_build/
```
# compress-archive uses backslash and fails on non-Windows platforms

```
$ unzip -l ~/compress-archive-bad.zip
Archive:  /home/mike/compress-archive-bad.zip
Length      Date    Time    Name
---------  ---------- -----   ----
    305    2019-04-03 16:25   node_modules\.bin\semver
    182    2019-04-03 16:25   node_modules\.bin\semver.cmd
    0      2019-04-04 12:41   node_modules\bson\lib\
    460    1985-10-26 09:15   node_modules\bson\bower.json
    7674   1985-10-26 09:15   node_modules\bson\HISTORY.md
    1457   1985-10-26 09:15   node_modules\bson\index.js
    11357  1985-10-26 09:15   node_modules\bson\LICENSE.md
```
# Proposed solution

Since Windows Explorer already uses /, it would be safe for `compress-archive` to do the same on all platforms.

**Comment by SteveL-MSFT** [comment]
This is a dupe that's been fixed.  Plan is for @anmenaga to publish new version to the gallery next week.  We can pick up the new version in 6.2.1 and 7.0

**Comment by anmenaga** [comment]
Updated module is on the PSGallery;
`Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force`

**Comment by mikemaccana** [comment]
Thnaks!

PS for anyone else: use:

`Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force`
