### ISSUE TITLE
Add Exclude parameter to Compress-Archive

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/Microsoft.PowerShell.Archive#84]
Currently we can not filter out files (directories) from source tree.

Comes from https://github.com/PowerShell/PowerShell/issues/9321#issuecomment-580582929

Proposal:
```powershell
Compress-Archive -Exclude '*.pdb'
Compress-Archive -Exclude 'foldername'
```

Can be implemented based on `Get-Children -Exclude`.

/cc @SteveL-MSFT

**Comment by 2asgwkq4m** [comment]
yes, that's a feature
