### ISSUE TITLE
According to the doc output is System.IO.FileInfo but cmdlet returns nothing

### ISSUE THREAD

**Issue by eosfor** [PowerShell/Microsoft.PowerShell.Archive#9]
According to the doc output is System.IO.FileInfo but cmdlet returns nothing
https://technet.microsoft.com/en-us/library/dn841358.aspx

**Comment by SteveL-MSFT** [comment]
The behavior is addressed via https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/18, however this is now a doc bug.  I don't think we want to change the default behavior as it would break existing scripts.

**Comment by sdwheeler** [comment]
This was fixed in MicrosoftDocs/PowerShell-Docs#3696 on Feb 12. You need to run Update-Help -Force to get the new help files.
